# Generated by Django 5.1.7 on 2025-03-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='year_of_experience',
            new_name='years_of_experience',
        ),
    ]
