# Generated by Django 5.1.7 on 2025-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Booked'), ('R', 'Reserving'), ('F', 'Finished')], default='A', max_length=10),
        ),
    ]
